# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 03:40
from __future__ import unicode_literals

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_location_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='thumb',
            field=models.ImageField(default='catalog/images/icon.png', upload_to=catalog.models.image_upload_to),
        ),
    ]
