# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 03:41
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_location_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='thumb',
            field=imagekit.models.fields.ProcessedImageField(upload_to='catalog/images'),
        ),
    ]
